### ISSUE TITLE
AsyncStorage has been extracted from react-native core and will be removed in a future release.

### ISSUE THREAD

**Issue by Gismo1337** [kiyohken2000/ReactNative-Expo-Firebase-Boilerplate-v2#2]
First of all - you are my hero. i struggle two days long to get this **** done. but there is a little warning to watch out in the next month.
```
AsyncStorage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-async-storage/async-storage' instead of 'react-native'. See https://github.com/react-native-async-storage/async-storage
at node_modules/react-native/Libraries/Utilities/warnOnce.js:27:2 in warnOnce
at node_modules/react-native/index.js:300:12 in module.exports.get__AsyncStorage
at node_modules/@firebase/app/dist/index.rn.cjs.js:615:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/firebase/dist/index.rn.cjs.js:3:22 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at src/firebase/config.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at src/scenes/login/Login.js:6:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at src/scenes/login/index.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at src/routes/navigation/stacks/LoginNavigator.js:7:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at src/routes/navigation/stacks/index.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at src/routes/navigation/Navigation.js:8:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at src/routes/navigation/index.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at src/routes/Routes.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at src/routes/index.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at src/App.js:12:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at src/index.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at App.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:349:11 in loadModuleImplementation
at node_modules/expo/AppEntry.js:3:0 in <global>
- ... 4 more stack frames from framework internals
```

**Comment by kiyohken2000** [comment]
Thank you for your contribution. Thank you very much.

That warning is probably caused by auth in firebase web sdk.
It may be solved by upgrading to firebase v9.

**Comment by kiyohken2000** [comment]
I updated to Firebase v9 and it fixed the warning.

So far only auth is using the new Firebase, Firestore and Storage are using the compat package.
